name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:

  Deploy-Production:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
